File_Header=<body>        Settlers: Fallen Empire       </body>

Prologue=			<body><img src="Prologue.png"/></body>

Start_Imperial=		<body><img src="Start_Imperial.png"/></body>
Start_Dwarf=		<body><img src="Start_Dwarf.png"/></body>
Start_Elf=			<body><img src="Start_Elf.png"/></body>
Start_Merefolk=		<body><img src="Start_Merefolk.png"/></body>
Start_Celestial=	<body><img src="Start_Celestial.png"/></body>

Start_Dragonkin=	<body><img src="Start_Dragonkin.png"/></body>

Start_AlAnfa=		<body><img src="Start_AlAnfa.png"/></body>
Start_Orcs=			<body><img src="Start_Orcs.png"/></body>
Start_Undead=		<body><img src="Start_Undead.png"/></body>
Start_Demon=		<body><img src="Start_Demon.png"/></body>
Start_Ratkin=		<body><img src="Start_Ratkin.png"/></body>


NotifyAmago=<body>My Lord, <b>Amago</b> and their allies are close to Victory!<br><br>   What shall we do?<br><br></body>
NotifyAmago_sounds=Warning
NotifyDate=<body>My Lord, <b>Date</b> and their allies are close to Victory!<br><br>   What shall we do?<br><br></body>
NotifyDate_sounds=Warning

VictoryAmago=<body>My Lord, <b>Amago</b> and their allies have won!<br><br>   But who will be Shogun?<br><br></body>
VictoryDate=<body>My Lord, <b>Date</b> and their allies have won!<br><br>   But who will be Shogun?<br><br></body>
